### ISSUE TITLE
font-size html VS body, em/rem confus

### ISSUE THREAD

**Issue by rastapopougros** [tcharlss/minitinytypo#1]
Oui j'ai pas réussi à trouver un titre compréhensible.

J'ai l'impression qu'il y a une confusion entre l'endroit où est défini la font-size "racine".

Quand on est dans un module CSS, dans des sous-sous-sous balises, qui ont pu potentiellement agrandir ou rétrécir la police, on utilise alors "rem" pour être sûr que tel style soit basé sur la taille de base de la racine qui est toujours la même, tandis que le "em" a pu être changé par 12 parents successifs.

Sauf que… la police racine c'est celle de la balise "html" ! Or là ya une définition des écritures de base dans "body". Ce qui fait que partout les "em" partent de la police racine calc() responsive, et que les lignes de base ont cette taille là. Mais "1rem" continue de valoir 16px du navigateur par défaut pour toujours. Et donc "em" et "rem" n'ont plus rien à voir du tout, ne sont plus du tout basé sur la même chose. Alors que "rem" doit servir à "revenir au em de départ" normalement.

Autrement dit : le "1em" à la racine, n'a pas du tout la même valeur que "1rem" ! Ce qui est assez incongru et pas intuitif, et surtout pas pratique du tout.

Par exemple, souvent on met des tailles de conteneurs en "em" par ex `max-width:60em`, et dans tous les thèmes qu'on a fait, c'était bien en "em" donc bien par rapport à la taille _responsive_ qui est en calc(). Sauf que si jamais dans telle section d'une page on a agrandit ou rétrécit globalement avec par ex `.masection{ font-size: 1.2em }` et bien si on met un conteneur comme décrit précédemment dedans, il a va pas du tout avoir la même taille ! Et donc pour être carré la logique voudrait que les conteneurs ne dépendent pas des divers parents aléatoires qu'il peut y avoir au-dessus, ça devrait être `max-width : 60rem`. Sauf que quand on fait ça c'est tout pété puisque le "rem" vaut 16px fixe et non pas le calc() responsive qui est utilisé partout !

**Comment by rastapopougros** [comment]
Généralement la plupart des articles qui expliquent la typo fluide définissent bien tout ça sur le "html".

Mais si ça dépend des gens/des thèmes, certaines pourraient vouloir une typo fluide mais baser les "rem" sur 16px tandis que d'autres veulent baser les "rem" sur la même taille que le "em" fluide (ce qui devrait être le par défaut il me semble car c'est le comportement de base où 1rem=1em sans changement de parent), alors il faudrait que ce soit configurable dans les settings. Genre par défaut c'est sur le "html" mais si seulement ya telle variable à true, alors c'est défini sur le "body".

Au passage je vois plutôt un calcul avec un min ET un max (au delà d'une certaine taille d'écran, ça n'augmente plus).

Au passage bis plus tard ya une super fonction CSS clamp() qui sera encore plus simple pour faire de la typo fluide :
https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()
mais pour l'instant ya encore un peu trop de nav pour qui ça marche pas

**Comment by rastapopougros** [comment]
TL;DR :
-  Par défaut, le réglage de la taille responsive devrait être sur l'élément "html", afin que 1rem = 1em par défaut (quand on entre pas dans des balises qui changent les tailles).
- Il me semble que ça suffit pour toujours, juste on change ça et basta.
- Mais si vraiment, vraiment certaines personnes, pour certains sites, voudraient dissocier, il pourrait y avoir une variable de config qui si définie remet la définition sur "body" (mais ça complique le code pour du très hypothétique il me semble).

**Comment by tcharlss** [comment]
J'avais presque oublié ce ticket avec tout ça dis-donc :p

Alors le font-size est mis sur le body [comme dans tiny-typo](https://github.com/tetue/tinytypo/blob/master/less/typo.less#L16), j'avais laissé ça tel quel sans me poser plus de question.

Mais oui, c'est à déplacer sur l'élément html, dans la majorité des cas on veut une concordance entre le rem et le em.
Je pense même pas qu'il soit nécessaire de faire une option compliquée pour le mettre sur le body.

Sur la question de la taille de la police responsive et du rythme vertical, il faudrait aussi remettre à plat à un moment : voir s'il est vraiment utile de sa base sur une lib alors que quelques règles de base pourraient suffire (et Shevy n'est plus maintenue), voir s'il n'y a pas mieux/plus simple pour gérer les espacements (un truc fonction de la taille de police), etc.

**Comment by rastapopougros** [comment]
Pour la typo fluide *et toutes les autres tailles d'espacement*, j'avais noté ça l'autre jour, qui est une micro lib dédiée faite par Twitter et désormais comme base de Bootstrap 5, mais utilisable seule : 
https://github.com/twbs/rfs

**Comment by tcharlss** [comment]
Ouais merci, ça à l'air pas mal du tout.

En parlant de bootstrap ils procèdent encore autrement d'ailleurs : ils mettent le font-size sur le body, et pour les rem ils mettent un font-size sur le :root : https://github.com/twbs/bootstrap/blob/main/scss/_reboot.scss#L29

````scss
// Ability to the value of the root font sizes, affecting the value of `rem`.
// null by default, thus nothing is generated.
:root {
  font-size: $font-size-root;
}
body {
  @include font-size($font-size-base);
}
````

Et [les variables](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L412-L415) :
````scss
// $font-size-root effects the value of `rem`, which is used for as well font sizes, paddings and margins
// $font-size-base effects the font size of the body text
$font-size-root:              null !default;
$font-size-base:              1rem !default; // Assumes the browser default, typically `16px`
````

Pas sûr de suivre le procédé, faudra que je relise tout ça.
